---
- name: my test playbook
  hosts: all
  become: true
  tasks:
  - name: stop httpd
    service:
       name: httpd
       state: stopped
  - name: uninstalled httpd pkg
    yum:
      name: httpd
      state: removed
